accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

# 앱 이름 명시하기
app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name="accountapp/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

almighty/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likeapp/urls.py
from django.urls import path
from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'


urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models


# Create your models here.

# 클래스 하나가 item 하나가 된다 !
class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)  # 공백 X 문자열 필드

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render  # alt+enter로 import 가능
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld

# 계정 소유 확인 decorator
from articleapp.models import Article

has_ownership = [account_ownership_required, login_required]


@login_required
def hello_world(request):
    if request.method == "POST":
        # create
        temp = request.POST.get('hello_world_input')

        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))

    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/helloworld.html', context={'hello_world_list': hello_world_list})


class AccountCreateView(CreateView):
    # CreateView에 필요한 주요 파라미터 지정
    model = User  # 장고 기본 Model, AbstractUser 클래스 이용 필드 추가 가능
    form_class = UserCreationForm
    success_url = reverse_lazy("home")  # reverse_lazy -> 클래스형, reverse -> 함수형
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'
    paginate_by = 16

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)


# get(), post()는 클래스 안에 있는 함수, 즉 메서드이므로 @login_required가 적용되지 않음 !
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):  # 파라미터가 create와 거의 동일하다
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy("accountapp:hello_world")  # reverse_lazy -> 클래스형, reverse -> 함수형
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.user.pk})


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy("accountapp:hello_world")
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="account_form_div">
        <div>
            <h3><strong>Sign Up</strong></h3>
            <hr>
        </div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-warning" value="sign up">
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div>
    <div class="account_form_div">
        <div style="margin: 0.5rem;">
            <h3><strong>Quit</strong></h3>
            <hr>
        </div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <p>⚠️ 회원 탈퇴는 곧바로 진행됩니다. 주의하세요! </p>
            <input type="submit" value="quit" class="btn btn-danger">
        </form>
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="list_div">
    <div>
    {% if target_user.profile %}
            <img src="{{ target_user.profile.image.url }}" alt="profile image" class="profile_img">
            <h2>{{ target_user.profile.nickname }}
                {% if target_user == user %}
                    <a class="material-icons"
                       style="box-shadow: 0 0 3px #ccc; border-radius: 10rem; padding: 0.4rem;"
                       href="{% url 'profileapp:update' pk=target_user.profile.pk %}">edit</a>
                {% endif %}
            </h2>
            <h5>{{ target_user.profile.message }}</h5>

    {% else %}
        {% if target_user == user %}
        <h3><a href="{% url 'profileapp:create' %}">Create Profile</a></h3>
        {% else %}
        <h3>no profile</h3>
        {% endif %}
    {% endif %}
    </div>

    {% if target_user == user %}
        <a href="{% url 'accountapp:update' pk=user.pk %}">
            change account info
        </a><br>
        <a href="{% url 'accountapp:delete' pk=user.pk %}">
            quit
        </a>
    {% endif %}

    <hr>
</div>

<div>
    {% include 'snippets/list_fragment.html' with article_List=object_list %}
</div>
{% endblock %}

accountapp/templates/accountapp/helloworld.html
{% extends 'base.html' %}

<!-- content block 내부의 내용을 작성 -->
{% block content %}

    <div style="text-align: center; background-color: #548f00; border-radius: 1rem; margin: 2rem; padding: 1rem;">
        <h2>testing</h2>

        <form action="/account/hello_world/" method="POST">
            {% csrf_token %}
            <div style="margin: 1rem;">
                <input type="text" name="hello_world_input">
            </div>
            <div>
                <input type="submit" class="btn btn-warning" value="POST">
            </div>
            {% if hello_world_output %}
                {{ hello_world_output.text }}
            {% endif %}
        </form>
        <hr>
        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
                <div>
                {{ hello_world.text }}
                </div>
            {% endfor %}
        {% endif %}


    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div>
    <div class="account_form_div">
        <div style="margin: 0.5rem;">
            <h3><strong>Login</strong></h3>
            <hr>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="login" class="btn btn-warning">
            <a href="{% url 'accountapp:create' %}"><h6>SignUp</h6></a>
        </form>
    </div>
</div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="account_form_div">
        <div>
            <h3><strong>Change Info</strong></h3>
            <hr>
        </div>
        <form action="{% url 'accountapp:update' pk=target_user.pk%}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-warning" value="apply">
        </form>
    </div>
{% endblock %}