accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

# 앱 이름 명시하기
app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name="accountapp/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

almighty/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleDeleteView, ArticleUpdateView, ArticleListView

app_name = "articleapp"

urlpatterns = [
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(template_name='articleapp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(template_name='articleapp/detail.html'), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(template_name='articleapp/update.html'), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(template_name='articleapp/delete.html'), name='delete'),
]

likeapp/urls.py
from django.urls import path
from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectDetailView, ProjectCreateView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family:'MaruBuri-Regular'">
    {% include 'header.html' %}

    {% for message in messages %}
    <div class="text-center">
        <div class="btn btn-{{ message.tags }} rounded-pill px-5 my03">
            {{ message }}
        </div>
    </div>

    {% endfor %}

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="footer_div">
    <hr>
    <div class="footer_button">
        <span>| notice | </span>
        <span>introduce | </span>
        <span>contact |</span>
    </div>
    <div>
        <a href="{% url 'home' %}" class="home_link">
            <h6 class="almighty_logo">almighty life</h6>
        </a>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Almighty Life</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- bootstrap link -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Cormorant:ital@0;1&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap" rel="stylesheet">

    <!-- default style sheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css'%}">

    <!-- @font-face -->
    <style>
        @font-face {
            font-family: 'MaruBuri-Regular';
            src: local('MaruBuri-Regular');
            url("{% static 'fonts/MaruBuri-Regular.otf' %}") format("opentype");
        }
    </style>

    <!-- material icons -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">
</head>

templates/header.html
    <div class="header_div">
        <div>
            <a href="{% url 'home' %}" class="home_link">
                <h1 class="almighty_logo">✨ Almighty Life ✨</h1>
            </a>
        </div>
        <div>
            <a href="{% url 'projectapp:list' %}" class="header_nav">
                    <span>Projects</span>
            </a>
            <a href="{% url 'subscribeapp:list' %}" class="header_nav">
                    <span>Subscription</span>
            </a>
            <a href="{% url 'articleapp:list' %}" class="header_nav">
                    <span>Articles</span>
            </a>
            {% if not user.is_authenticated %}
                <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="header_nav">
                    <span>Login</span>
                </a>
                <a href="{% url 'accountapp:create' %}" class="header_nav">
                    <span>Sign Up</span>
                </a>
            {% else %}
                <a href="{% url 'accountapp:detail' pk=user.pk %}" class="header_nav">
                    <span>My Page</span>
                </a>
                <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="header_nav">
                    <span>Logout</span>
                </a>

            {% endif %}
        </div>
    </div>
    <hr>