almighty/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleDeleteView, ArticleUpdateView, ArticleListView

app_name = "articleapp"

urlpatterns = [
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(template_name='articleapp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(template_name='articleapp/detail.html'), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(template_name='articleapp/update.html'), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(template_name='articleapp/delete.html'), name='delete'),
]

likeapp/urls.py
from django.urls import path
from likeapp.views import LikeArticleView

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>', LikeArticleView.as_view(), name='article_like'),
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

from projectapp.models import Project


class Article(models.Model):
    # 회원 탈퇴 시 작성자는 알 수 없음 등으로 표시
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    img = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)
    created_at = models.DateField(auto_now_add=True, null=True)

    like = models.IntegerField(default=0)

articleapp/forms.py
import django.forms
from django.forms import ModelForm
from django import forms

from articleapp.models import Article
from projectapp.models import Project


class ArticleCreationForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'editable text-left',
                                                           'style': 'height: auto;'}))
    project = forms.ModelChoiceField(queryset=Project.objects.all(), required=False)

    class Meta:
        model = Article
        fields = ['title', 'img', 'project', 'content']

articleapp/views.py
from django.contrib.auth.decorators import login_required

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article
from commentapp.forms import CommentCreationForm


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    context_object_name = 'target_article'
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.writer = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    context_object_name = 'target_article'
    form_class = ArticleCreationForm
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = "target_article"
    template_name = 'articleapp/delete.html'

    def get_success_url(self):
        return reverse('articleapp:list')


class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_List'
    template_name = 'articleapp/list.html'
    paginate_by = 8

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-editor.min.css"
      type="text/css" media="screen" charset="utf-8">

    <div class="account_form_div">
        <div>
            <h3><strong>Create an Article</strong></h3>
            <hr>
        </div>
        <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-warning" value="upload">
        </form>
    </div>

<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div>
    <div class="account_form_div">
        <div style="margin: 0.5rem;">
            <h3><strong>Delete Article <{{ target_article.title }}></strong></h3>
            <hr>
        </div>
        <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post">
            {% csrf_token %}
            <p>⚠️ 게시글 삭제는 곧바로 진행됩니다. 주의하세요! </p>
            <input type="submit" value="delete" class="btn btn-danger">
        </form>
    </div>
</div>
{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="account_form_div">
        <h3 style="padding-bottom: 2rem;">{{ target_article.title }}</h3>
        <div style="height: 2rem;">
            <a href="{% url 'likeapp:article_like' pk=target_article.pk %}">
                <i style="vertical-align: middle; font-size: 1.2rem; color: #f77" class="material-icons">
                    favorite
                </i>
                <span style="vertical-align: middle; font-size: 1.2rem;">
                {{ target_article.like }}
            </span>
            </a>
        </div>

        <h5><div style="display: flex; justify-content: space-between;">
            {% if target_article.writer.profile.nickname %}
                <span>writer : {{ target_article.writer.profile.nickname }}</span>
                {% if target_article.writer == user %}
                    <span style="">
                        <a href="{% url 'articleapp:update' pk=target_article.pk %}">
                            Update
                        </a>&nbsp&nbsp
                        <a href="{% url 'articleapp:delete' pk=target_article.pk %}">
                            Delete
                        </a>
                    </span>
                {% endif %}
            {% else %}
                <span>writer : unknown</span>
            {% endif %}
        </div></h5>

        <hr>
        <img src="{{ target_article.img.url }}" alt="{{ target_article.title }}" style="width: 100%; border-radius: 1rem; margin: 2rem 0;">
        <h5 style="text-align: left;">
            {{ target_article.content | safe }}
        </h5>
        <hr>


        {% for comment in target_article.comment.all %}
            <div class="comment_div">
                {% include 'commentapp/detail.html' with comment=comment %}
            </div>
        {% endfor %}

        {% include 'commentapp/create.html' with article=target_article %}
    </div>
{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>
.container {
  padding: 0;
  margin: 0 auto;
}

.container a {
  width: 45%;
  max-width: 250px;
  padding: 0.5rem;
}

.container div {
  display: flex;
  justify-content: center;
  align-items: center;
  border-radius: 8px;
}

.container img {
  width: 100%;
  border-radius: 1rem;
}

</style>
  {% if article_List %}
    <div class="container">
      {% for article in article_List %}
        <a href="{% url 'articleapp:detail' pk=article.pk %}">
          {% include 'snippets/card.html' with article=article %}
        </a>
      {% endfor %}
    </div>
    <script src="{% static 'js/magicgrid.js' %}"></script>
  {% else %}
    <div class="footer_div">
      <h3>No Articles Yet!</h3>
    </div>
  {% endif %}

  {% include 'snippets/pagination.html' with page_obj=page_obj %}

  <div class="footer_div">
      <a href="{% url 'articleapp:create' %}" class="btn btn-warning">
        Create Article
      </a>
  </div>





{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/medium-editor.min.css"
      type="text/css" media="screen" charset="utf-8">

    <div class="account_form_div">
        <div>
            <h3><strong>Edit Article</strong></h3>
            <hr>
        </div>
        <form action="{% url 'articleapp:update' pk=target_article.pk%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-warning" value="apply">
        </form>
    </div>

<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}